In [ ]:
# # 주피터노트북 셀 스타일 조절
# from IPython.core.display import display, HTML
# # display(HTML("<style>.container { font-weight: bold !important; }</style>"))
# display(HTML("<style>.container { width: 100% !important; }</style>"))

# # 경고메시지 숨기기
# import warning
# warnings.filterwarnings(action='ignore')

# Numpy 개요
```
Numeric + Python = Numpy
수학 및 과학 연산을 위한 파이썬 패키지
배열이나 행렬 계산에 용이한 메서드를 제공
한글로 넘파이로 주로 통칭, 넘피/늄파이라고 부르기도 함
관련 사이트 : http://www.numpy.org
일반 List에 비해 빠르고, 메모리 효율적

반복문 없이 데이터 배열에 대한 처리를 지원함
선형대수와 관련된 다양한 기능을 제공함
Reference Site
cs231 : http://cs231n.github.io/python-numpy-tutorial/#numpy
https://docs.scipy.org/doc/numpy-dev/user/quickstart.html
데이터사이언스스쿨(파이썬버전) - https://goo.gl/3hsjbS
설치 및 임포트
넘파이는 외부 라이브러리이므로 설치 필요.(아나콘다는 사전 설치됨)
pip install numpy
```

In [ ]:
import numpy as np
np.__version__

## 넘파이 배열 이해하기

## ndim(dimention, rank)
몇 차원인지 반환

In [ ]:
a = np.array(0)
a, a.ndim, type(a)

In [ ]:
a = np.array([2, 4, 6])
a, a.ndim, type(a)

In [ ]:
a = [ 
    [1,2,3],
    [4,5,6] 
]
a


In [ ]:
a = np.array(a)
a, a.ndim, type(a)


In [ ]:
a = np.array([
    [
        [
            1,
            2,
            3],
        [4,5,6]],
    [[1,2,3],[4,5,6]]
])


a, a.ndim, type(a)

In [ ]:
a.flatten()

## shape
행렬의 차원으로, 몇행 몇열인지 반환

In [ ]:
a.shape

In [ ]:
a.shape?

In [ ]:
a = np.array(3)
a, a.shape # 행렬이 아니기 때문

In [ ]:
a = np.array([1, 
              3, 
              5, 
              7, 
              9])
a, a.ndim ,a.shape

In [ ]:
a = np.array([ 
    [1,2,3],
    [4,5,6] 
    ])
a, a.shape

In [ ]:
a = np.array([
    [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]],
    [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
])

a,a.size,len(a), a.shape # 2개의 3행 4열

In [ ]:
a.ndim

## 넘파이 배열
* 리스트를 넘파이 배열로 생성 np.array(리스트)
* 관련 속성 : ndim 차원 반환 int , size 전체 길이 반환 int, shape 구조 반환 tuple

In [ ]:
# 1차원 리스트 객체(이터러블)
myList = [10, 56, 77, 23, 44]
print(myList, type(myList), len(myList))

In [ ]:
myArr = np.array(myList)
print(myArr, type(myArr), len(myArr))
print(f'차원={myArr.ndim}, 구조={myArr.shape}, size={myArr.size}, 길이={len(myArr)}')

In [ ]:
# 2차원 리스트 객체(이터러블)
myList2 = [
           [1,2,3 ],
           [10,20,30],
           [100,200,300]
          ]
myList2, len(myList2)

In [ ]:
myArr2 = np.array(myList2)
print(myArr2, type(myArr2), len(myArr2))
print(f'차원= {myArr2.ndim}, 구조 = {myArr2.shape}, size = {myArr2.size}, 길이={len(myArr2)}' )

In [ ]:
# 2차원 리스트에서 각 행의 수가 다를 경우?
myList21 = [ 
        [1,2,3,4],
        [10,20,30,40,50],
        [100,200,]
        ]
print(myList21, type(myList21), len(myList21))

In [ ]:
# 길이가 달라 에러 리턴
myArr21 = np.array(myList21)
#print(myArr21, type(myArr21), len(myArr21))
#print(f'차원= {myArr21.ndim}, 구조 = {myArr21.shape}, size = {myArr21.size}')

## 넘파이 배열과 리스트와의 차이점
* 배열간의 연산 가능 "브로드캐스팅", 요소별 연산(element-wise)
* 넘파이 메서드 사용 가능 : 평균, 상관계수, 분산, 표준편차 등
* 리스트는 자료형 혼합 가능, 넘파이배열은 하나의 자료형만 가능

In [ ]:
# 리스트의 산술연산자 +, * 
import numpy as np
listA = [10, 30, 50]
listB = [1, 2, 3]
print(listA + listB) # 리스트의 + 연산자는 조인역할
print(listA + 2) # 불가

In [ ]:
print(listA * 2) # 해당 리스트의 반복
print(listA * listB) # 불가

In [ ]:
# 넘파이의 산술연산
import numpy as np
arrA = np.array([1, 2, 3])
lis = [1,2,3]
print(arrA + 2)
print(arrA * 2)
print(lis * 2)

In [ ]:
arrB = np.array([4, 5, 6])
print(arrA + arrB)
print(arrA * arrB)
print(arrA / arrB)
print(arrA // arrB) # 몫
print(arrA % arrB) # 나머지

## dtype
```
https://numpy.org/doc/stable/reference/arrays.dtypes.html
데이터 U유형은 각 유니코드 문자를 32비트 정수(예: 4바이트)로 저장합니다. (유니코드 스트링 dtype 인수로 지정할 자료형은 다음 표에 보인것과 같은 “dtype 접두사”로 시작하는 문자열이고 이 글자 뒤에 오는 숫자는 바이트 수 혹은 글자 수를 의미한다.
예를 들어 f8은 8바이트(64비트) 부동소수점 실수를 뜻하고 U4 는 4글자 유니코드 문자열을 뜻한다
숫자를 생략하면 운영체제에 따라 알맞은 크기를 지정한다.
```

In [ ]:
# 자료형 테스트
myList_c = ['안녕', 100, 3.14, True, False] # 리스트는 혼합된 형 그대로 유지
print(myList_c)

In [ ]:
myArr_c = np.array(myList_c) # 넘파이배열은 '문자열'로 통일 자동형변환
print(myArr_c, type(myArr_c), myArr_c.dtype)

In [ ]:
# 정수와 실수가 혼합된 넘파이 배열
myArr_d = np.array([100, 3.14, 23.5, 0])
print(myArr_d, type(myArr_d), myArr_d.dtype) # 정수와 실수 혼합시, 더 큰 실수형으로 통일 자동형변환

## Inf와 NaN
```
넘파이에서는 무한대를 표현하기 위한 np.inf(infinity)와 정의할 수 없는 숫자를 나타내는 np.nan(not a number)을 사용할 수 있다.
다음 예와 같이 1을 0으로 나누려고 하거나 0에 대한 로그 값을 계산하면 무한대인 np.inf이 나온다.
0을 0으로 나누려고 시도하면 np.nan이 나온다.
```

In [ ]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])


In [ ]:
np.log(0)

In [ ]:
np.exp(-np.inf)

## 기술통계 

In [ ]:
import pandas as pd 

x = np.array([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
              2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

s = pd.Series([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
              2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13] ,name="hello")
s



In [ ]:
df

In [ ]:
x.mean(), s.mean()


In [ ]:
np.mean(x),s.mean()

In [ ]:
# 분산
np.var(x), s.var()

In [ ]:
# 표준편차
np.std(x), s.std()

In [ ]:
# 최대
np.max(x), s.max()

In [ ]:
# 최소
np.min(x), s.min()

In [ ]:
# 중앙값
np.median(x), s.median()

## 사분위수
```
사분위수(quartile)는 데이터를 가장 작은 수부터 가장 큰 수까지 크기가 커지는 순서대로 정렬하였을 때 1/4, 2/4, 3/4 위치에 있는 수를 말한다.
각각 1사분위수, 2사분위수, 3사분위수라고 한다.
1/4의 위치란 전체 데이터의 수가 만약 100개이면 25번째 순서, 즉 하위 25%를 말한다. 따라서 2사분위수는 중앙값과 같다.

때로는 위치를 1/100 단위로 나눈 백분위수(percentile)을 사용하기도 한다. 1사분위수는 25% 백분위수와 같다.
```

In [ ]:
x = np.array([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
              2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])
print(x.sort())
print(x)

np.percentile(x, 0) # 최소값

In [ ]:
np.percentile(x, 25) # 1사분위수

In [ ]:
np.percentile(x, 50) # 2사분위수

In [ ]:
np.percentile(x, 75) # 3사분위수

In [ ]:
np.percentile(x, 100) # 최대값

## 넘파이 함수로 배열 만들기
```
np.ones(n) , np.ones((x, y))
np.zeros(n) , np.zeros((x, y))
np.empty(n) , np.empty((x, y))
np.aranges(start, end step)

reshape(x, y) # 차원 확대
flatten(x, y) # 차원 축소
```

In [ ]:
# 1로 메모리 초기화, 넘파이 함수로 배열을 만들때에는 디폴트가 실수형
print(np.ones(10), np.ones(10).dtype) 

In [ ]:
np.ones(10,dtype=np.int64)


In [ ]:
print(np.ones((2,4)), np.ones((2,4)).dtype)

In [ ]:
print(np.ones(10, dtype = int), np.ones(10, dtype = int).dtype)

In [ ]:
# 0으로 메모리 초기화
print(np.zeros(10), np.zeros(10).dtype)

In [ ]:
print(np.zeros((3,3)), np.zeros((3,3)).dtype)

In [ ]:
# 메모리가 비어있음 -> 메모리가 초기화 되지 않는다.
print(np.empty(10), np.empty(10).dtype)
print(np.empty((3,3)), np.empty((3,3)).dtype)
print(np.empty((3,3)))
print(np.empty((3,3), dtype=int))  # 기존 메모리에 있던 값을 출력한다.(정확히 알수 없음)

In [ ]:
# 리스트+레인지
print( list(range(1,21)), type(list(range(1,21))) )

In [ ]:
# 1~20으로 구성된 4행 5열의 넘파이 배열print(np.array(list(range(1,21))), type(list(range(1,21))))
print(np.arange(20), type(np.arange(20)))
print(np.arange(1, 20), type(np.arange(1, 20)))
print(np.arange(1, 20, 2), type(np.arange(1, 20,2)))

In [ ]:
# linspace 명령이나 logspace 명령은 선형 구간 혹은 로그 구간을 지정한 구간의 수만큼 분할한다.
np.linspace(0, 100)  # 시작, 끝(포함), 갯수

In [ ]:
np.linspace?

In [ ]:
np.logspace?

In [ ]:
np.logspace(-11111111111111, 111111111, 10)

## reshape 구조의 재배열
```
reshape함수는 np.reshape(변경할 배열, 차원) 또는 배열.reshape(차원)으로 사용 할 수 있으며,
현재의 배열의 차원(1차원,2차원,3차원)을 변경하여 행렬을 반환하거나 하는 경우에 많이 이용되는 함수이다.
```

In [ ]:
# 0~49까지 구성된 넘파이 배열
arr = np.arange(1,51) 
print(arr, len(arr), arr.size)

In [ ]:
arr, arr.ndim, arr.shape

In [ ]:
arr = arr.reshape(10,5) 
arr, arr.ndim, arr.shape


In [ ]:
arr2 = arr.reshape(5,10)
arr2, arr2.ndim, arr2.shape

In [ ]:
arr2 = arr.reshape(4,10)
arr2, arr2.ndim, arr2.shape

In [ ]:
# 2차원 -> 1차원
# 넘파이배열.flatten()
arr3 = arr2.flatten()
arr3, arr3.shape, arr3.ndim

In [ ]:
# 1~100 사이의 짝수로 된 넘파이 배열 생성
np.arange(2,101,2)

In [ ]:
np.arange(2,101,2).reshape(5, 10)

In [ ]:
np.arange(1, 31)

In [ ]:
# 2차원인데 1개 칼럼의 모형을 만들어보자
# reshape(-1, n) : 2차원 n개의 컬럼으로 구성, -1을 넣으면 자동으로 사이즈를 맞춰준다.
arr4 = np.arange(1, 31).reshape(3, -1)
arr4, arr4.ndim, arr4.shape

## quiz : 5행 4열로 이루어진 모형을 만들어보자
5행 4열

In [ ]:
np.arange(1, 21).reshape(5, 4)

In [ ]:
# -1 사용해서, 5열인 모형으로 바꿔보세요.
np.arange(1, 21).reshape(-1, 5)

In [ ]:
# 사이즈는 맞아야 합니다.
np.arange(1, 21).reshape(-1, 7)

In [ ]:
a = np.arange(12)
a, a.shape

In [ ]:
a.shape = 2, -1
a, a.shape

In [ ]:
a.shape = 3, -1
a, a.shape

In [ ]:
a.shape = -1, 1
a, a.shape

In [ ]:
# flatten
a.shape = -1
a, a.shape

## 넘파이배열의 자료형 형변환
* 배열명2 = 배열명1.astype(자료형)
* 자료형 = np.float64, np.int32

In [ ]:
matrix1 = np.arange(1, 10)
matrix1, matrix1.dtype

In [ ]:
# 정수형, 3행 3열
matrix = np.arange(1, 10).reshape(3,3)
matrix, matrix.dtype

In [ ]:
# 실수형, 3행 3열
matrix = np.arange(1, 51, dtype=float).reshape(5,10)
matrix, matrix.dtype

In [ ]:
# 문자열형, 3행 3열 -> 불가
matrix = np.arange(1, 10, dtype='str').reshape(3,3)
matrix, matrix.dtype

In [ ]:
# 정수형 => 문자열
matrix.astype('<U5').astype("float")

In [ ]:
# 논리형으로 구성된 넘파이 배열 생성
matrix2 = np.array([True, False, True, True])
matrix2, matrix2.dtype

In [ ]:
# 불린 -> 정수
matrix2.astype(int)


In [ ]:
# 불린형 -> 문자열
matrix2.astype('<U5')

In [ ]:
# 문자열 숫자 => 정수 , 실수
matrix3 = np.array(['3.14', '5.5', '0.78'])
matrix3, matrix3.dtype

In [ ]:
print(matrix3.astype(float))

print(matrix3.astype(int)) # 불가
print(matrix3.astype(bool)) # 불가

In [ ]:
print(matrix3.astype(float))

In [ ]:
matrix4 = np.array(['3', '5', '7'])
matrix4.astype(int)  # 가능, 값이 유효하기 때문

## 넘파이 배열의 인덱싱

넘파이배열[index] 넘파이배열[i, j], 넘파이배열[i][j] : i행 j 열

###  1D array

In [ ]:
a = np.array([1, 3, 5, 7, 9])
a, a.ndim, a.shape, a.size

In [ ]:
a[0]

In [ ]:
a[4]

In [ ]:
a[-1]

In [ ]:
a[ [0,2,4] ]

In [ ]:
# 행렬구조도 인덱싱이 가능하다.
b = np.array([
    [1, 3],
    [4, 2]
] )
b

In [ ]:
# 넘파이 배열1을 넘파이 배열2로 인덱싱하는 경우, 넘파이배열2는 인덱스 번호로 인식
a[b]

In [ ]:
print(a)
a[2] = 0
print(a)

In [ ]:
a[1] += 2
a

In [ ]:
a[0] += 6
a

### 2D array

In [ ]:
a = np.arange(15).reshape(3, 5)
a, a.ndim, a.shape, a.size

In [ ]:
# 인덱싱값이 하나일 경우에는 행 인덱싱
a[0]

In [ ]:
a[1]

In [ ]:
# 인덱싱값이 2개 들어가면 행/열 인덱싱
a[0, 0]

In [ ]:
a[1, 3]

In [ ]:
a[2][ 4]

In [ ]:
a[-1, -1]

In [ ]:
a[-1][-1]

In [ ]:
# 값 변경
a = np.arange(15).reshape(3, -1)
a

In [ ]:
a[1] = [1, 3, 5, 7, 9]
a

In [ ]:
a[-1] = 10
a

In [ ]:
a[0] += [1, 2, 3, 4, 5]
a

## 넘파이배열 슬라이싱
```
1차원
넘파이배열[:end]
넘파이배열[start:]
넘파이배열[start:end]
넘파이배열[start:end:step]

2차원
넘파이배열[행, 열] = [start:end:step, start2:end2:step2]
```

### 1D array

In [ ]:
a = np.array([1, 3, 5, 7, 9])
a, a.ndim, a.shape, a.size

In [ ]:
a[:]

In [ ]:
a[1:]

In [ ]:
a[-1:]

In [ ]:
a[1:4]

In [ ]:
a = np.arange(10)
a

In [ ]:
# 홀수 뽑기
a[1::2]

In [ ]:
# 거꾸로 나열해보세요
a[::-2]

### 2D array

In [9]:
import numpy as np

In [11]:
a = np.arange(10, 25).reshape(3, 5)
a, a.ndim, a.shape, a.size

(array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]),
 2,
 (3, 5),
 15)

In [13]:
a[1:]

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [15]:
a[:-3]

array([], shape=(0, 5), dtype=int32)

In [17]:
a[1:][1:] # 행의 범위, 열의 범위

array([[20, 21, 22, 23, 24]])

In [19]:
a[1:,1:]

array([[16, 17, 18, 19],
       [21, 22, 23, 24]])

In [ ]:
a[:,4:]

In [ ]:
a[: , -1:]

In [ ]:
a

In [ ]:
a[1:, 2:3]

In [ ]:
a[:2, 1:4]

In [ ]:
a[:-1, 1:-1]

In [ ]:
a[1, 2]

In [ ]:
a[1][2]

In [ ]:
a

In [ ]:
# 행 뒤집기
a[::-1]

In [ ]:
# 열 뒤집기
a[::, ::-1]

## 전치행렬

In [ ]:
# 3행 2열
matrix_d = np.arange(1,7).reshape(3,2)
matrix_d

In [ ]:
# 2행 3열로 변환
print(matrix_d.T)

In [ ]:
# reshape과 transpose은 값이 다름을 유의 (reshape는 flatten이 선행)
print(matrix_d.flatten())
print(matrix_d.reshape(2,3)) 

## 난수로 구성된 넘파이 배열
* np.random.randint(start, end, n) : 정수 난수
* np.random.randint(start, end, (i, j))

In [ ]:
np.random.randint?

In [ ]:
# 1~10 사이의 숫자중에서 10개 출력
np.random.randint(1, 10, 10)

In [ ]:
np.random.randint(1, 49, 6)

In [ ]:
# 2행 5열로 츨력
np.random.randint(1, 10, (2,5))

## 섞기
* np.random.shuffle(넘파이배열) 원본에 바로 적용

In [ ]:
np.random.shuffle?

In [ ]:
# 10개 무작위 값 만들기
matrix_e = np.arange(1,11).reshape(5,2)
matrix_e

In [ ]:
np.random.shuffle(matrix_e)
matrix_e

## Quiz : 1~45까지 구성된 숫자 중에서 6개를 뽑아서 로또 번호를 생성하라

In [ ]:
num= np.arange(1,46)
np.random.shuffle(num)
num[:6]

In [ ]:
np.random.randint(1,46,6)

## 실수 난수
* np.random.randn(n)
* np.random.randn(i, j)

In [ ]:
np.random.randn?

In [ ]:
matrix1 = np.random.randn(10) # 표준정규분포 0 ~ 분산1
matrix1

In [ ]:
matrix2 = np.random.randn(4, 4)
matrix2

In [ ]:
matrix1.max(), matrix1.min()

In [ ]:
#p, r, e
#parameter
#optional -> default
#

#np.random.choice([1,2,3])
#np.random.choice(np.arange(4))

#np.random.choice([1,2,3],2)
#np.random.choice([1,2,3],(2,2))
#np.random.choice([1,2,3],4,replace=True)
#np.random.choice([1,2,3,4],4,replace=False)
#aa_milne_arr = ['pooh', 'rabbit', 'piglet', 'Christopher']
#np.random.choice(aa_milne_arr, 5,p=[0.25, 0.25, 0.25, 0.25])


#if a is an int and less than zero, 
#np.random.choice(-1)
#np.arange(-1) 

#if a or p are not 1-dimensional,
#np.random.choice([[1,2,3,4],[5,6,7,8]])

#if a is an array-like of size 0, 
#np.random.choice([])

#if p is not a vector of probabilities, 
#np.random.choice([1,2,3],3,True,[0.1,0.2,0.2])
#np.random.choice([1,2,3],3,p=[0.1,0.2,0.7])
#np.random.choice([1,2,3],3,p=[0.1,0.2,0.2])

#if a and p have different lengths,
#np.random.choice([1,2],3,p=[0.1,0.2,0.7])

#if replace=False and the sample size is greater than the population size
#np.random.choice([1,2,3],4,replace=False)

#def choice(k) :
#    if k<0 :
#        raise ValueError(" 0 보다 작아요")
#    np.arange(-1)
#choice(-1)



In [ ]:
np.random.choice?

## 집계함수에서의 축
* 2차원에서의 집계합수(sum, mean)
* axis = 0, 1
* np.sum(넘파이배열, axis=0/1)
* np.mean(넘파이배열, axis=0/1)
* np.sort(넘파이배열, axis=0/1)

In [ ]:
m1 = np.random.randint(1, 10, (5,5))
m1

In [ ]:
m1[0,::]

In [ ]:
#np.sum?

In [ ]:
np.sum(m1, axis=0) # (x)열 합계(행방향 합계

In [ ]:
np.sum(m1, axis=1) #행합계 (열방향 합계)

## quiz

In [ ]:
# 1번째행의 합계는
m1[0,:]

In [ ]:
np.sum(m1[0,:], axis=0)

In [ ]:
# 3번째 열의 합계
np.sum(m1[:, 2], axis=0)

## np.sort()

In [ ]:
# 정수 난수로 구성된 4x3
m2 = np.random.randint(1, 50,(4,3,3))
m2



In [ ]:
#np.sort?

In [ ]:
np.sort(m2,axis=1) # 행안에서 열정렬 # default axis = -1 마지막 축을 따라 정렬

In [ ]:
m2

In [ ]:
np.sort(m2, axis=0) # 열정렬(행방향) 오름차순(요소별로)

In [ ]:
m2[::-1, ::-1] # 행전체가 역순으로 바뀌는 것과는 다르다(sort는 +요소별 정렬까지 해줌)

In [ ]:
m2

In [ ]:
np.sort(m2, axis=1) # 행정렬(열방향 오름차순)

In [ ]:
m2[::-1, ::-1] 

## 인덱스 소팅
np.argsort(넘파이배열, axis=0,1)

정렬값을 인덱스로 반환 (np.sort()를 인덱스로)

In [ ]:
x = np.array([9,5,4])
np.argsort(x) # 오름차순 정렬 4 5 9 의 인덱스 값 

In [ ]:
x[np.argsort(x)] # 인덱스값으로 실제 값 출력

## 넘파이 배열 요소 추가와 삭제
```
삽입

np.insert(배열, 위치인덱스, 값, axis=0/1)
2차원인 경우 axis를 설정하지 않으면 1차원 배열로 변경되어 삽입출력
삭제

np.delete(배열명, 위치인덱스, axis=0/1)
```

In [ ]:
m3 = np.arange(1,11)
m3

In [ ]:
np.insert?

In [ ]:
np.insert(m3, 0, 100)

In [ ]:
m3[0]

In [ ]:
np.insert(m3, -1, 500)  # 인덱싱/슬라이싱 end처럼 인식

In [ ]:
len(m3)
m3

In [ ]:
m3 = [5,4,3,5,6]
np.insert(m3, len(m3), 500)

In [ ]:
m4 = np.arange(1,13).reshape(3,4)
m4

In [ ]:
np.insert(m4, 0, 100) # 2차원배열의 경우 axis 미설정시 1차원으로 변경되어 삽입

In [ ]:
# 1열으로 [100,100,100] 삽입
np.insert(m4, 0, 100, axis=0)


In [ ]:
# 리스트로 삽입
np.insert(m4, 0, [100,200,300], axis=1)   

In [ ]:
m4.shape, m4.shape[1], len(m4)

In [ ]:
# 마지막 컬럼으로 삽입
#배열명.shape[1] 칼럼 길이
np.insert(m4, m4.shape[1] , [100,200,300], axis=1)


In [ ]:
# 마지막 행에 삽입
np.insert(m4, m4.shape[0], [100,200,300], axis=0)

In [ ]:
m4, m4.shape

In [ ]:
np.delete(m4, 1, axis=1)

## 배열 합치기
* np.vstack((배열1,배열2....)) : 세로 합치기
* np.hstack((배열1,배열2....)) : 가로 합치기
* np.concatenate((배열1, 배열2), axis=0/1 ) 2차원만 가능

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.hstack((a,b))


In [ ]:
np.hstack((a,b)), np.hstack((a,b)).ndim, np.hstack((a,b)).shape

In [ ]:
c = np.array( [
    [1,2,3]
] ) # 2차원
c, c.ndim, c.shape

In [ ]:
d = np.array([
    [4,5,6]
]) # 2차원
d, d.ndim, d.shape

In [ ]:
f = np.concatenate((c,d), axis=0) #
f, f.ndim, f.shape

In [ ]:
f = np.concatenate((c,d), axis=1) #
f, f.ndim, f.shape

## boolean indexing, mask
* 조건절의 결과는 True, False로 반환
* True인 결과의 데이터 반환
* 넘파이배열[조건절] : ==, !=, <=, >=, &, |, ~

In [ ]:
matrix = np.arange(1, 21)
matrix

In [ ]:
matrix > 10

In [ ]:
matrix[matrix > 10]

In [ ]:
len(matrix[matrix > 10])

In [ ]:
np.sum(matrix > 10)

## Quiz : 1~100사이 난수 30개를 추출하여 넘파이 배열을 생성하고, 30보다 크거나 70보다 작은 수를 출력하라

In [ ]:
num = np.random.randint(1, 100, 30)
(num > 30) & (num < 70)

In [ ]:
num[(num > 30) & (num < 70)]

In [ ]:
# ~은 revere를 의미
num[~(num > 30) ]

## 10보다 작거나 90보다 큰수 출력하기

In [ ]:
# 10보다 작거나 90보다 큰 수,
(num < 10)
(num > 15)
((num < 10) | (num > 80))

In [ ]:
(num > 80)
num[((num < 10) | (num > 80))]

## fancy indexing(filtering)
```
넘파이 배열에 배열로 인덱싱하면 인덱스 번호로 인식한다.

넘파이배열1[넘파이배열2]
넘파이배열2 : 인덱스 역할 (only 정수형)
```

In [ ]:
n = np.random.randint(1,100,30)
i = np.array([0, 2, 3, 10, 20])
n, n[i]

## np.where()를 이용한 필터링
* np.where(조건식) : 조건식 만족하는 인덱스 반환
* np.where(조건식, T, F) : 조건식 만족하면 T값, 아니면F값
* 배열[np.where(조건식)] : 조건식 만족하는 실제 배열값

In [ ]:
np.where?

In [ ]:
a = np.arange(10)
a, np.where(a < 5, a, 10*a)
# a가 5보다 작으면 a를, 아니면 10을 곱하여 출력

In [ ]:
b = np.arange(20, 31)
b, np.where(b<25) # 조건을 하나만 주면 인덱스를 반환함

In [3]:
import pandas as pd

a=pd.DataFrame([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]], columns=["a","b","c","d"])
a


a   b   c   d
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12

In [ ]:
pd.DataFrame({"a":[1,5,9],"b":[2,6,10],"c":[3,7,11],"d":[4,8,12]})

In [5]:
pd.DataFrame([{"a":1,"b":2,"c":3,"d":4},
              {"a":5,"b":6,"c":7,"d":8},
              {"a":9,"b":10,"c":11,"d":12}])

a   b   c   d
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12

In [ ]:
zip([1,5,9],[2,6,10])

In [ ]:
for i in zip([1,5,9],[2,6,10],[3,7,11],[4,8,12]):
    print(i)