In [3]:
import numpy as np

In [43]:
a = np.arange(15, dtype=np.int64).reshape(3,5, order="F")
print(a)

[[ 0  3  6  9 12]
 [ 1  4  7 10 13]
 [ 2  5  8 11 14]]


In [41]:
print(type(a))
print(a.shape)
print(a.dtype)
print(a.ndim)
print(a.size)
# print(dir(np))

<class 'numpy.ndarray'>
(3, 5)
int64
2
15


In [75]:
array = [1,2,3,4,5]
array2 = [6,7,8,9,10]
new_array = []
for i in array :
    new_array.append(i)
print(new_array)
print("=====")



array_sum = [array,array2]
new_array_sum = []
for i in array_sum :
    new_array_sum.append(i)
print(new_array_sum)
print("=====")

array_sum = [array,array2]
new_array_sum = []
for i in array_sum :
    print(i)
    print("-----")
print("=====")


array_sum = [array,array2]
new_array_sum = []
for i in array_sum :
    for j in i:
        print(j)
    print("-----")
print("=====")


array_sum = [array,array2]
for i in array_sum :
    inner = []
    for j in i :
        inner.append(j)
    print(inner)
    print("-----")
print("=====")


new_array_sum = []
for i in array_sum :
    inner = []
    for j in i :
        inner.append(j)
    new_array_sum.append(inner)
print(new_array_sum)
    

[1, 2, 3, 4, 5]
=====
[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
=====
[1, 2, 3, 4, 5]
-----
[6, 7, 8, 9, 10]
-----
=====
1
2
3
4
5
-----
6
7
8
9
10
-----
=====
[1, 2, 3, 4, 5]
-----
[6, 7, 8, 9, 10]
-----
=====
[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]


In [119]:
b = np.array([-1,2,5,-3,0,7,-9,7,-4,-7],dtype=np.int64)
# print(b.reshape(2,5,order="F"))

In [85]:
t = (10,20,30,40,50)
print(type(t))
t = np.array(t)
print(type(t))

<class 'tuple'>
<class 'numpy.ndarray'>


In [105]:
t = np.array("hello2")
print(type(t))
print(t.size)
r = t.reshape(2,3)

<class 'numpy.ndarray'>
1


ValueError: cannot reshape array of size 1 into shape (2,3)

In [103]:
s = {10,20,30,40,50}
s = np.array(s)
print(type(s))

<class 'numpy.ndarray'>


In [121]:
print(b.shape)
print(b.ndim)
print(b.dtype)
print(b)

(10,)
1
int64
[-1  2  5 -3  0  7 -9  7 -4 -7]


In [123]:
print(np.abs(b))

[1 2 5 3 0 7 9 7 4 7]


In [127]:
print(np.sqrt(abs(b)))

[1.         1.41421356 2.23606798 1.73205081 0.         2.64575131
 3.         2.64575131 2.         2.64575131]


In [129]:
print(np.square(b))

[ 1  4 25  9  0 49 81 49 16 49]


In [133]:
print(np.isnan(np.sqrt(b)))

[ True False False  True False False  True False  True  True]


C:\Users\min\AppData\Local\Temp\ipykernel_23092\3348548598.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.isnan(np.sqrt(b)))


In [147]:
print(b)
print(np.sum(b))
print(np.sort(b))
print(np.mean(b))
print(np.max(b))
print(np.min(b))
print(np.argmax(b))

[-1  2  5 -3  0  7 -9  7 -4 -7]
-3
[-9 -7 -4 -3 -1  0  2  5  7  7]
-0.3
7
-9
5
