In [3]:
import numpy as np

In [43]:
a = np.arange(15, dtype=np.int64).reshape(3,5, order="F")
print(a)

[[ 0  3  6  9 12]
 [ 1  4  7 10 13]
 [ 2  5  8 11 14]]


In [41]:
print(type(a))
print(a.shape)
print(a.dtype)
print(a.ndim)
print(a.size)
# print(dir(np))

<class 'numpy.ndarray'>
(3, 5)
int64
2
15


In [75]:
array = [1,2,3,4,5]
array2 = [6,7,8,9,10]
new_array = []
for i in array :
    new_array.append(i)
print(new_array)
print("=====")



array_sum = [array,array2]
new_array_sum = []
for i in array_sum :
    new_array_sum.append(i)
print(new_array_sum)
print("=====")

array_sum = [array,array2]
new_array_sum = []
for i in array_sum :
    print(i)
    print("-----")
print("=====")


array_sum = [array,array2]
new_array_sum = []
for i in array_sum :
    for j in i:
        print(j)
    print("-----")
print("=====")


array_sum = [array,array2]
for i in array_sum :
    inner = []
    for j in i :
        inner.append(j)
    print(inner)
    print("-----")
print("=====")


new_array_sum = []
for i in array_sum :
    inner = []
    for j in i :
        inner.append(j)
    new_array_sum.append(inner)
print(new_array_sum)
    

[1, 2, 3, 4, 5]
=====
[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
=====
[1, 2, 3, 4, 5]
-----
[6, 7, 8, 9, 10]
-----
=====
1
2
3
4
5
-----
6
7
8
9
10
-----
=====
[1, 2, 3, 4, 5]
-----
[6, 7, 8, 9, 10]
-----
=====
[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]


In [119]:
b = np.array([-1,2,5,-3,0,7,-9,7,-4,-7],dtype=np.int64)
# print(b.reshape(2,5,order="F"))

In [85]:
t = (10,20,30,40,50)
print(type(t))
t = np.array(t)
print(type(t))

<class 'tuple'>
<class 'numpy.ndarray'>


In [105]:
t = np.array("hello2")
print(type(t))
print(t.size)
r = t.reshape(2,3)

<class 'numpy.ndarray'>
1


ValueError: cannot reshape array of size 1 into shape (2,3)

In [103]:
s = {10,20,30,40,50}
s = np.array(s)
print(type(s))

<class 'numpy.ndarray'>


In [121]:
print(b.shape)
print(b.ndim)
print(b.dtype)
print(b)

(10,)
1
int64
[-1  2  5 -3  0  7 -9  7 -4 -7]


In [123]:
print(np.abs(b))

[1 2 5 3 0 7 9 7 4 7]


In [127]:
print(np.sqrt(abs(b)))

[1.         1.41421356 2.23606798 1.73205081 0.         2.64575131
 3.         2.64575131 2.         2.64575131]


In [129]:
print(np.square(b))

[ 1  4 25  9  0 49 81 49 16 49]


In [133]:
print(np.isnan(np.sqrt(b)))

[ True False False  True False False  True False  True  True]


C:\Users\min\AppData\Local\Temp\ipykernel_23092\3348548598.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.isnan(np.sqrt(b)))


In [156]:
print(b)
print(np.sum(b))
print(np.mean(b))
print(np.max(b))
print(np.min(b))
print(np.argmax(b))
print(np.argmin(b))
print(np.sort(b))
print(np.sort(b)[::-1])
print(np.median(b))

[-1  2  5 -3  0  7 -9  7 -4 -7]
-3
-0.3
7
-9
5
6
[-9 -7 -4 -3 -1  0  2  5  7  7]
[ 7  7  5  2  0 -1 -3 -4 -7 -9]
-0.5


In [192]:
c = [[ 1,2,3,],
     [4,5,6]]
print(type(c))
print(c)
c = np.array(c)
print(type(c))
print(c)
print(np.sum(c))
print(np.sum(c, axis=0))
print(np.sum(c, axis=1))
print(np.mean(c))
print(np.mean(c, axis=0))
print(np.mean(c, axis=1))

print(np.std(c, axis=0))
print(np.var(c, axis=0))

<class 'list'>
[[1, 2, 3], [4, 5, 6]]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
21
[5 7 9]
[ 6 15]
3.5
[2.5 3.5 4.5]
[2. 5.]
[1.5 1.5 1.5]
[2.25 2.25 2.25]


In [212]:
d = [10,20,30,40,50]
print(d)
d = np.array(d)
print(d+2)

e = np.array([1,2,3,4,5])
print(d + e)
print(d ** 2)
print(d * np.sin(d))
print(d > 35 )

print(np.add(d,e))
print(np.subtract(d,e))
print(np.multiply(d,e))
print(np.divide(d,e))

[10, 20, 30, 40, 50]
[12 22 32 42 52]
[11 22 33 44 55]
[ 100  400  900 1600 2500]
[ -5.44021111  18.25890501 -29.64094872  29.80452642 -13.11874269]
[False False False  True  True]
[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]


In [228]:
f = np.array([[0,1],[1,1]])
g = np.array([[2,0],[3,4]])

print(f+g)
print(f*g)
print(f@g)
print(np.dot(f,g))
print(f.dot(g))

[[2 1]
 [4 5]]
[[0 0]
 [3 4]]
[[3 4]
 [5 4]]
[[3 4]
 [5 4]]
[[3 4]
 [5 4]]


In [242]:
h = np.zeros(10)
print(h)
h = np.zeros((5,5))
print(h)
h = np.ones(10)
print(h)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [256]:
# np.random.random
# np.random.randint
# np.random.rand
# np.random.randn
# np.random.nomral

k = np.random.random(10) * 100
k = np.array([int(i) for i in k])
print(type(k))
print(k)
k = np.random.random((5,5))
print(k)

<class 'numpy.ndarray'>
[62  2 23 31 59 20 30 96 10 68]
[[0.02021812 0.8304012  0.98753401 0.81740779 0.65363713]
 [0.92004896 0.14881062 0.37217204 0.85789946 0.70703077]
 [0.47446427 0.5337995  0.28100384 0.842754   0.64659632]
 [0.69497736 0.73225512 0.01457265 0.05918844 0.26114968]
 [0.42660666 0.59859002 0.94794138 0.2628342  0.7486167 ]]


In [260]:
k = np.random.randint(10,20,(5,5))
print(k)

[[13 15 17 16 17]
 [18 10 15 12 18]
 [14 17 12 18 16]
 [11 11 14 13 14]
 [14 15 17 14 12]]


In [270]:
m = np.random.randint(0,10,(5,5))


[[6 7 8 6 7]
 [6 1 7 1 9]
 [1 5 1 7 3]
 [4 1 4 5 6]
 [4 2 6 6 1]]


In [296]:
print(m[:2])

[[6 7 8 6 7]
 [6 1 7 1 9]]


In [310]:
w = np.arange(10,20)
print(w[0:5:2])

[10 12 14]


In [336]:
r = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]
print(r[0:2])
w = np.array(r)
print(w[0:2,0:2])

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
[[1 2]
 [6 7]]


In [342]:
s = np.arange(1,16).reshape(3,5)
print(s)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [352]:
print(s[2][2])
print(s[:][:])
print(s[::-1,::-1])
print(s[[0,2]])

13
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]
[[ 1  2  3  4  5]
 [11 12 13 14 15]]


In [354]:
print(s[:,[1,2,3]])

[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]


In [374]:
print(s[[0,2],[1,3]])

[ 2 14]


In [376]:
print(s)
print(s.T)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [398]:
a = [1,2,3]
b = [4,5,6]
for ab  in zip(a,b):
    print(ab)

print(list(zip(a,b)))
print(a+b)

(1, 4)
(2, 5)
(3, 6)
[(1, 4), (2, 5), (3, 6)]
[1, 2, 3, 4, 5, 6]


In [390]:
c = np.floor(np.random.rand(2,2)*100)
print(c)

d = np.floor(np.random.rand(2,2)*100)
print(d)

[[58. 61.]
 [29. 85.]]
[[82. 76.]
 [38. 33.]]


In [392]:
print(np.hstack((c,d)))

[[58. 61. 82. 76.]
 [29. 85. 38. 33.]]


In [394]:
(c,d)

(array([[58., 61.],
        [29., 85.]]),
 array([[82., 76.],
        [38., 33.]]))

In [396]:
print(np.vstack((c,d)))

[[58. 61.]
 [29. 85.]
 [82. 76.]
 [38. 33.]]


In [406]:
e = np.floor(np.random.rand(2,15)*100)
print(e)
print(np.hsplit(e,3))
print(np.hsplit(e,(3,7,12)))

[[54.  5. 38. 69. 36.  3. 97. 85. 11. 54. 31. 52.  3. 37. 14.]
 [80.  4. 94. 32. 35. 29. 21. 43. 40. 63. 82. 56. 98. 74. 97.]]
[array([[54.,  5., 38., 69., 36.],
       [80.,  4., 94., 32., 35.]]), array([[ 3., 97., 85., 11., 54.],
       [29., 21., 43., 40., 63.]]), array([[31., 52.,  3., 37., 14.],
       [82., 56., 98., 74., 97.]])]
[array([[54.,  5., 38.],
       [80.,  4., 94.]]), array([[69., 36.,  3., 97.],
       [32., 35., 29., 21.]]), array([[85., 11., 54., 31., 52.],
       [43., 40., 63., 82., 56.]]), array([[ 3., 37., 14.],
       [98., 74., 97.]])]


In [408]:
f = np.array([1,2,3,4,5])
g = np.array(['A','B','C','D','E'])
h = np.array([True,True,False,False,True])

In [410]:
print(f)
print(g)
print(h)

[1 2 3 4 5]
['A' 'B' 'C' 'D' 'E']
[ True  True False False  True]


In [414]:
print([[x,y,z] for x,y,z in zip(f,g,h)])

[[1, 'A', True], [2, 'B', True], [3, 'C', False], [4, 'D', False], [5, 'E', True]]


In [422]:
print([x if z else y for x,y,z in zip(f,g,h)])

[1, 2, 'C', 'D', 5]


In [428]:
print(np.where(h,f,g))
print(np.where(f<3, "작다","크다."))
print(np.where(h,'참','거짓'))


['1' '2' 'C' 'D' '5']
['작다' '작다' '크다.' '크다.' '크다.']
['참' '참' '거짓' '거짓' '참']


In [439]:
i = np.arange(10)
np.save('i.npy',i)
r = np.load('i.npy')
print(r)

j = np.arange(10)
k = np.arange(10)
np.savez('jk.npz',x=j, y=k )
jk = np.load('jk.npz')

print(jk['x'])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
