In [9]:
# Pandas
# Series                    1차원
# DataFrame                 2차원


import pandas as pd
import numpy as np
#Series

s = pd.Series( np.random.rand(100) )
print(type(s))
print(s.index)
print(s.dtype)
print(s)

<class 'pandas.core.series.Series'>
RangeIndex(start=0, stop=100, step=1)
float64
0     0.825194
1     0.957043
2     0.457772
3     0.521382
4     0.096820
        ...   
95    0.851265
96    0.701635
97    0.586147
98    0.635242
99    0.552264
Length: 100, dtype: float64


In [13]:
s = pd.Series( [1,2,3,4,5,6,7,8,9,10] )
print(type(s))
print(s.index)
print(s.dtype)
print(s)
s.index = ['A','B','C','D','E','F','G','H','I',"j"]
print(s)

<class 'pandas.core.series.Series'>
RangeIndex(start=0, stop=10, step=1)
int64
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64
A     1
B     2
C     3
D     4
E     5
F     6
G     7
H     8
I     9
j    10
dtype: int64


In [15]:
s = pd.Series([1,2,3,4,5,6,7,8,9],['A','B','C','D','E','F','G','H','I'])

In [29]:
print(s)
print(s.index)
print(s.values)
print(s[0])
print(s['A'])

A    1
B    2
C    3
D    4
E    5
F    6
G    7
H    8
I    9
dtype: int64
Index(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'], dtype='object')
[1 2 3 4 5 6 7 8 9]
1
1


C:\Users\min\AppData\Local\Temp\ipykernel_28060\793597647.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0])


In [33]:
m = [1,2,3,4,5,6,7,8,9]
print(m[0])

1


In [37]:
print(s.A)
print(s[0:5])
print(s['A':'D'])

1
A    1
B    2
C    3
D    4
E    5
dtype: int64
A    1
B    2
C    3
D    4
dtype: int64


In [39]:
d = {'A':10,'D':20,'F':30,'H':40}
print(type(d))

<class 'dict'>


In [51]:
print(type(d))
for key,value in d.items():
    print(key,":",value)
print(d['A'])
#print(d.A)

s = pd.Series(d)
print(s.index)
print(s.values)
print(s['A'])
print(s.A)



<class 'dict'>
A : 10
D : 20
F : 30
H : 40
10
Index(['A', 'D', 'F', 'H'], dtype='object')
[10 20 30 40]
10
10


In [53]:
d = {
    "name":['kim','lee','park','jung'],
    "age":[25,30,35,20],
    'tel':['1111-2222','2222-1111','3333-1111','2222-3333']    
}

print(type(d))

<class 'dict'>


In [65]:
df = pd.DataFrame(d)
print(df)
print(df.index)
print(df.values)
print(df.columns)
df.index.name = "NUM"
df.columns.name = "C"
print(df)
print(df.index)
print(df.values)
print(df.columns)

   name  age        tel
0   kim   25  1111-2222
1   lee   30  2222-1111
2  park   35  3333-1111
3  jung   20  2222-3333
RangeIndex(start=0, stop=4, step=1)
[['kim' 25 '1111-2222']
 ['lee' 30 '2222-1111']
 ['park' 35 '3333-1111']
 ['jung' 20 '2222-3333']]
Index(['name', 'age', 'tel'], dtype='object')
C    name  age        tel
NUM                      
0     kim   25  1111-2222
1     lee   30  2222-1111
2    park   35  3333-1111
3    jung   20  2222-3333
RangeIndex(start=0, stop=4, step=1, name='NUM')
[['kim' 25 '1111-2222']
 ['lee' 30 '2222-1111']
 ['park' 35 '3333-1111']
 ['jung' 20 '2222-3333']]
Index(['name', 'age', 'tel'], dtype='object', name='C')


In [73]:
# Numpy -> DataFrame
n = np.array([['kim',20,'1111-2222'],
             ['lee',30,'2222-1111'],
             ['park',35,'3333-2222'],
              ['jung',25,'3333-1111']
             ])

print(type(n))

df = pd.DataFrame(n)
print(df)
print(df.index)
print(df.columns)

df.columns = ['name','age','tel']
df.index = ['A','B','C','D']
print(df)
print(df.index)
print(df.columns)


<class 'numpy.ndarray'>
      0   1          2
0   kim  20  1111-2222
1   lee  30  2222-1111
2  park  35  3333-2222
3  jung  25  3333-1111
RangeIndex(start=0, stop=4, step=1)
RangeIndex(start=0, stop=3, step=1)
   name age        tel
A   kim  20  1111-2222
B   lee  30  2222-1111
C  park  35  3333-2222
D  jung  25  3333-1111
Index(['A', 'B', 'C', 'D'], dtype='object')
Index(['name', 'age', 'tel'], dtype='object')


In [75]:
df = pd.DataFrame(n,columns=['name','age','tel'])

In [77]:
print(df)

   name age        tel
0   kim  20  1111-2222
1   lee  30  2222-1111
2  park  35  3333-2222
3  jung  25  3333-1111


In [79]:
df = pd.DataFrame(n,columns=['name','age','tel'],index=['A','B','C','D'])
print(df)

   name age        tel
A   kim  20  1111-2222
B   lee  30  2222-1111
C  park  35  3333-2222
D  jung  25  3333-1111


In [81]:
print(df.describe())

       name age        tel
count     4   4          4
unique    4   4          4
top     kim  20  1111-2222
freq      1   1          1


In [97]:
print(df['name'])
print(df[['name','tel']])
#print(df['name'][2])
print(df['name'].C)
print(df['name']['B':'D'])

A     kim
B     lee
C    park
D    jung
Name: name, dtype: object
   name        tel
A   kim  1111-2222
B   lee  2222-1111
C  park  3333-2222
D  jung  3333-1111
park
B     lee
C    park
D    jung
Name: name, dtype: object


In [99]:
print(df.name,df.age)

A     kim
B     lee
C    park
D    jung
Name: name, dtype: object A    20
B    30
C    35
D    25
Name: age, dtype: object


In [101]:
print(df.name.C)

park


In [141]:
print(df[:][:])
print(df['name'][:2])

   name age        tel
A   kim  20  1111-2222
B   lee  30  2222-1111
C  park  35  3333-2222
D  jung  25  3333-1111
A    kim
B    lee
Name: name, dtype: object


In [117]:
print(df[:'C'])

   name age        tel
A   kim  20  1111-2222
B   lee  30  2222-1111
C  park  35  3333-2222


In [125]:
print(df[['name','tel']])
#print(df[[0,2]])

   name        tel
A   kim  1111-2222
B   lee  2222-1111
C  park  3333-2222
D  jung  3333-1111


In [143]:
print(df)
df['address'] = ['서울','수원','인천','안산']
print(df)

   name age        tel
A   kim  20  1111-2222
B   lee  30  2222-1111
C  park  35  3333-2222
D  jung  25  3333-1111
   name age        tel address
A   kim  20  1111-2222      서울
B   lee  30  2222-1111      수원
C  park  35  3333-2222      인천
D  jung  25  3333-1111      안산


In [165]:
df['age']=df['age'].astype(np.int64)

df['adult'] = df['age'] > 30
print(df)

   name  age        tel address  adult
A   kim   40  1111-2222      서울   True
B   lee   30  2222-1111      수원  False
C  park   35  3333-2222      인천   True
D  jung   25  3333-1111      안산  False


In [179]:
s = pd.Series([10,40,50,20,70,60],index=['a','r','c','g','e','f'])

s = s.sort_index(ascending=False)
print(s)
s = s.sort_values()
print(s)

r    40
g    20
f    60
e    70
c    50
a    10
dtype: int64
a    10
g    20
r    40
c    50
f    60
e    70
dtype: int64


In [ ]:
df = pd.DataFrame([[4,5,1,2],[20,10,40,30],['B','D','A','C']])

In [181]:
df = pd.DataFrame([[4,5,1,2],[300,400,200,100],[20,10,40,30]], index=['c','a','b'],columns=['D','C','A','B'])

In [183]:
print(df)

     D    C    A    B
c    4    5    1    2
a  300  400  200  100
b   20   10   40   30


In [207]:
df.sort_values("D")
df.sort_index()
df=df.sort_index(axis=0)
df.sort_index(axis=1,ascending=False)




D    C    B    A
a  300  400  100  200
b   20   10   30   40
c    4    5    2    1

In [227]:
#행끼리
df = df.sort_values(by='A', ascending=False)
print(df)
df = df.sort_values(by="A",ascending=False)
df = df.sort_values(by=['A','B'])

df = df.sort_values(by='b' ,axis=1)

print(df)

     A    B    C    D
a  200  100  400  300
b   40   30   10   20
c    1    2    5    4
     C    D    B    A
c    5    4    2    1
b   10   20   30   40
a  400  300  100  200


In [221]:
l = [["kim",30,"1111-2222"],["Lee",20,"2222-3333"],["Park",35,"1111-3333"],["Jung",40,"1111-2222"],["Hong",30,"1111-2222"]]



Kim
Lee
Park
Jung
Hong


In [233]:
print(df[:][:])
print(df[:2][:1])

#슬라이싱
# .iLoc
# .loc
# .ix              deprecated
# list

m = [[1,2,3],[4,5,6],[7,8,9]]


     C    D    B    A
c    5    4    2    1
b   10   20   30   40
a  400  300  100  200
   C  D  B  A
c  5  4  2  1


In [235]:
print(m)
print(m[2][2])
print(m[:][:])


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
9
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [237]:
print(m[:2][:2])

[[1, 2, 3], [4, 5, 6]]


In [241]:
# Numpy
n = np.array(m)
print(n)
print(n[2][2])
print(n[:2][:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
[[1 2 3]
 [4 5 6]]


In [243]:
print(n[:2,:2])

[[1 2]
 [4 5]]


In [249]:
# Pandas
df = pd.DataFrame(n)
print(df)
print(df[2][2])

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9
9


In [251]:
print(df[:][:])

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9


In [253]:
print(df[:2][:2])

   0  1  2
0  1  2  3
1  4  5  6


In [289]:
print(df[:1][:2])

   0  1  2
0  1  2  3


In [305]:
df = pd.DataFrame(np.arange(1,21).reshape(5,4),columns=['A','B','C','D'])
print(df)
print(df['C'][2])
print(df[['A','D']])

    A   B   C   D
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16
4  17  18  19  20
11
    A   D
0   1   4
1   5   8
2   9  12
3  13  16
4  17  20


In [335]:
df.iloc[2,2]
#print(df.iloc[2,2])
print(df.iloc[:2,:2])
print(df.iloc[:3:2,:3:2])
print(df.iloc[:3,:-1])
print(df.iloc[::-1,::-1])

   A  B
0  1  2
1  5  6
   A   C
0  1   3
2  9  11
   A   B   C
0  1   2   3
1  5   6   7
2  9  10  11
    D   C   B   A
4  20  19  18  17
3  16  15  14  13
2  12  11  10   9
1   8   7   6   5
0   4   3   2   1


In [347]:
print(df)
print(df.loc[2,"C"])

    A   B   C   D
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16
4  17  18  19  20
11


In [355]:
print(df.loc[:2,:"C"])

   A   B   C
0  1   2   3
1  5   6   7
2  9  10  11


In [361]:
df['E'] =[31,32,33,34,35]

In [379]:
df.iloc[4,:] = [1,2,3,4,5]

In [381]:
df

A   B   C   D   E
0   1   2   3   4  31
1   5   6   7   8  32
2   9  10  11  12  33
3  13  14  15  16  34
4   1   2   3   4   5

In [383]:
df.loc[5] = [2,3,4,5,6]

In [385]:
print(df)

    A   B   C   D   E
0   1   2   3   4  31
1   5   6   7   8  32
2   9  10  11  12  33
3  13  14  15  16  34
4   1   2   3   4   5
5   2   3   4   5   6


In [389]:
df.loc[:,'F'] = [40,41,42,43,44,45]

In [391]:
print(df)

    A   B   C   D   E   F
0   1   2   3   4  31  40
1   5   6   7   8  32  41
2   9  10  11  12  33  42
3  13  14  15  16  34  43
4   1   2   3   4   5  44
5   2   3   4   5   6  45


In [393]:
df.loc[0,'A']=99

In [395]:
print(df)

    A   B   C   D   E   F
0  99   2   3   4  31  40
1   5   6   7   8  32  41
2   9  10  11  12  33  42
3  13  14  15  16  34  43
4   1   2   3   4   5  44
5   2   3   4   5   6  45


In [397]:
df.loc[1,"A":"C"] =[100,101,102] 

In [399]:
print(df)

     A    B    C   D   E   F
0   99    2    3   4  31  40
1  100  101  102   8  32  41
2    9   10   11  12  33  42
3   13   14   15  16  34  43
4    1    2    3   4   5  44
5    2    3    4   5   6  45


In [401]:
df.loc[1,"A":"E":2] =[3,2,1] 

In [403]:
print(df)

    A    B   C   D   E   F
0  99    2   3   4  31  40
1   3  101   2   8   1  41
2   9   10  11  12  33  42
3  13   14  15  16  34  43
4   1    2   3   4   5  44
5   2    3   4   5   6  45


In [405]:
del(df['E'])

In [407]:
print(df)

    A    B   C   D   F
0  99    2   3   4  40
1   3  101   2   8  41
2   9   10  11  12  42
3  13   14  15  16  43
4   1    2   3   4  44
5   2    3   4   5  45


In [409]:
df.drop(0)

A    B   C   D   F
1   3  101   2   8  41
2   9   10  11  12  42
3  13   14  15  16  43
4   1    2   3   4  44
5   2    3   4   5  45

In [411]:
df.drop(3)

A    B   C   D   F
0  99    2   3   4  40
1   3  101   2   8  41
2   9   10  11  12  42
4   1    2   3   4  44
5   2    3   4   5  45

In [413]:
df.drop("F",axis=1)

A    B   C   D
0  99    2   3   4
1   3  101   2   8
2   9   10  11  12
3  13   14  15  16
4   1    2   3   4
5   2    3   4   5

In [451]:
df = pd.DataFrame([['kim',20,'1111-2222'],
             ['lee',30,'2222-1111'],
             ['park',35,'3333-2222'],
              ['jung',25,'3333-1111'],
              ['hong',40,'1111-2222']
             ],columns=['name','age','tel'])
print(df)
print(df.loc[3,'name'])
print(df.loc[[True,False,True,False,False],['name','age']])
print(df.loc[df["age"]>30,['name','age']])
print(df.loc[df["name"]=='kim',['name','age']])
print(df.loc[( df['age'] >20 ) & (df['age']<40),'name':'tel'])

   name  age        tel
0   kim   20  1111-2222
1   lee   30  2222-1111
2  park   35  3333-2222
3  jung   25  3333-1111
4  hong   40  1111-2222
jung
   name  age
0   kim   20
2  park   35
   name  age
2  park   35
4  hong   40
  name  age
0  kim   20
   name  age        tel
1   lee   30  2222-1111
2  park   35  3333-2222
3  jung   25  3333-1111


In [561]:
df = pd.DataFrame([['kim',20,'1111-2222'],
             ['lee',30,'2222-1111'],
             ['park',35,'3333-2222'],
              ['jung',25,'3333-1111'],
                   ['hong',40,"1111-3333"]
             ],)


# 결측값 대체
df.columns = ["name","age","phone"]
df['address'] = ['서울', np.nan,np.nan,"수원",np.nan]


In [563]:
df.loc[df['address'].isnull(),'address']="서울"



In [541]:
df.loc[::2,'address'] =''

In [565]:
df

name  age      phone address
0   kim   20  1111-2222      서울
1   lee   30  2222-1111      서울
2  park   35  3333-2222      서울
3  jung   25  3333-1111      수원
4  hong   40  1111-3333      서울

In [543]:
df.loc[df['address']=='','address'] = '서울'

In [545]:
# 결측값 제거
df.dropna()

name  age      phone address
0   kim   20  1111-2222      서울
1   lee   30  2222-1111      서울
2  park   35  3333-2222      서울
3  jung   25  3333-1111      수원
4  hong   40  1111-3333      서울

In [579]:
df.loc[::2,'phone'] = np.nan
df.loc[5,:] = [np.nan, np.nan, np.nan, np.nan]
#df.dropna(how='all', inplace=True)
df.dropna(how="any", inplace=True)
#print(df)

In [581]:
df

name   age      phone address
1   lee  30.0  2222-1111      서울
3  jung  25.0  3333-1111      수원

In [611]:
df = pd.DataFrame([['kim',20,'1111-2222','서울'],
             ['lee',30,'2222-1111',np.nan],
             ['park',35,'3333-2222','수원'],
              ['jung',25,'3333-1111',np.nan],
                   ['hong',40,"1111-3333",'서울']
             ])
df.columns = ["name","age","tel","address"]

df.loc[5,:] = [np.nan, np.nan, np.nan, np.nan]

In [613]:
df['income'] = [300, np.nan, 400, 500, np.nan,300] 
print(df)

   name   age        tel address  income
0   kim  20.0  1111-2222      서울   300.0
1   lee  30.0  2222-1111     NaN     NaN
2  park  35.0  3333-2222      수원   400.0
3  jung  25.0  3333-1111     NaN   500.0
4  hong  40.0  1111-3333      서울     NaN
5   NaN   NaN        NaN     NaN   300.0


In [617]:
df.fillna({'address':"서울"},inplace=True)

In [619]:
df

name   age        tel address  income
0   kim  20.0  1111-2222      서울   300.0
1   lee  30.0  2222-1111      서울     NaN
2  park  35.0  3333-2222      수원   400.0
3  jung  25.0  3333-1111      서울   500.0
4  hong  40.0  1111-3333      서울     NaN
5   NaN   NaN        NaN      서울   300.0

In [623]:
df.fillna({'income':np.mean(df['income'])},inplace=True)

In [627]:
df.drop([4,5],inplace=True)

In [629]:
df.drop(['address','income'],axis=1,inplace=True)

In [631]:
df

name   age        tel
0   kim  20.0  1111-2222
1   lee  30.0  2222-1111
2  park  35.0  3333-2222
3  jung  25.0  3333-1111

In [633]:
print(df.T)

              0          1          2          3
name        kim        lee       park       jung
age        20.0       30.0       35.0       25.0
tel   1111-2222  2222-1111  3333-2222  3333-1111


In [635]:
print(df.transpose())

              0          1          2          3
name        kim        lee       park       jung
age        20.0       30.0       35.0       25.0
tel   1111-2222  2222-1111  3333-2222  3333-1111


In [647]:
np.mean(df["age"])

27.5

In [655]:
df = pd.DataFrame([['kim',90,80,70],['lee',45,np.nan,55],['park',76,77,83],['hong',np.nan,np.nan,77],['kang',35,58,52],['jang',np.nan,np.nan,np.nan]],columns=['name','kor','eng','mat'])

In [671]:
print(df)
print(df.count())
print(df.count(axis=1))
print(df.min())
print(df.max())
print(df.loc[:,'kor':'eng'].min())

   name   kor   eng   mat
0   kim  90.0  80.0  70.0
1   lee  45.0   NaN  55.0
2  park  76.0  77.0  83.0
3  hong   NaN   NaN  77.0
4  kang  35.0  58.0  52.0
5  jang   NaN   NaN   NaN
name    6
kor     4
eng     3
mat     5
dtype: int64
0    4
1    3
2    4
3    2
4    4
5    1
dtype: int64
name    hong
kor     35.0
eng     58.0
mat     52.0
dtype: object
name    park
kor     90.0
eng     80.0
mat     83.0
dtype: object
kor    35.0
eng    58.0
dtype: float64


In [697]:
print(df.loc[:,'kor':].mean())
print(df.loc[:,'kor':].mean(axis=1))

kor    61.500000
eng    71.666667
mat    67.400000
dtype: float64
0    80.000000
1    50.000000
2    78.666667
3    77.000000
4    48.333333
5          NaN
dtype: float64


In [707]:
print(df.sum())
print(df.loc[:,'kor':'mat'].sum())

name    kimleeparkhongkangjang
kor                      246.0
eng                      215.0
mat                      337.0
dtype: object
kor    246.0
eng    215.0
mat    337.0
dtype: float64


In [713]:
print(df.loc[:,'kor':'mat'].median())

kor    60.5
eng    77.0
mat    70.0
dtype: float64


In [715]:
print(df.cumsum())

                     name    kor    eng    mat
0                     kim   90.0   80.0   70.0
1                  kimlee  135.0    NaN  125.0
2              kimleepark  211.0  157.0  208.0
3          kimleeparkhong    NaN    NaN  285.0
4      kimleeparkhongkang  246.0  215.0  337.0
5  kimleeparkhongkangjang    NaN    NaN    NaN


In [727]:
print(df.loc[:,'kor':'mat'].median())
#print(df.loc[:,'kor':'mat'].mad())
print(df.loc[:,'kor':'mat'].var())
print(df.loc[:,'kor':'mat'].std())

kor    60.5
eng    77.0
mat    70.0
dtype: float64
kor    665.666667
eng    142.333333
mat    183.300000
dtype: float64
kor    25.800517
eng    11.930353
mat    13.538833
dtype: float64


In [731]:
df['tot'] = df.loc[:,'kor':'mat'].sum( axis=1 )

In [735]:
print(df.transpose().T)

   name   kor   eng   mat    tot
0   kim  90.0  80.0  70.0  240.0
1   lee  45.0   NaN  55.0  100.0
2  park  76.0  77.0  83.0  236.0
3  hong   NaN   NaN  77.0   77.0
4  kang  35.0  58.0  52.0  145.0
5  jang   NaN   NaN   NaN    0.0


In [737]:
df['avg'] = df.loc[:,'kor':'mat'].mean(axis=1)

In [743]:
print(df['kor'].corr(df['eng']))

0.9926458576614517
